version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: tsiryti/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  
  vpromq01:
    image: "rabbitmq"
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  vprocache01:
    image: "memcached"
    ports:
      - "11211:11211"
  
  vproweb:
    build: 
      context: ./Docker-files/web
    image: tsiryti/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

  vproapp:
    build: 
      context: ./Docker-files/app
    image: tsiryti/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

volumes:
  vprodbdata: {}
  vproappdata: {}
  